/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import ConnectionProvider.ConnectingDatabase;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author 91898
 */
public class StudentResultPage extends javax.swing.JFrame {

    /**
     * Creates new form StudentResultPage
     */
    public StudentResultPage() {
        initComponents();
    }
    public StudentResultPage(String rollNo){
        initComponents();
        rollno_textField.setText(rollNo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rollno_textField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        name_tField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        gender_tField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        course_tField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fathername_tField = new javax.swing.JTextField();
        branch_tField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        total_tField = new javax.swing.JTextField();
        physics_tField = new javax.swing.JTextField();
        che_tField = new javax.swing.JTextField();
        maths_tField = new javax.swing.JTextField();
        ele_tField = new javax.swing.JTextField();
        biology_tField = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        verdict_tField = new javax.swing.JTextField();
        logoutButton = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 550));
        setMinimumSize(new java.awt.Dimension(600, 550));
        setPreferredSize(new java.awt.Dimension(600, 550));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Roll No.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));
        getContentPane().add(rollno_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 120, -1));

        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));
        getContentPane().add(name_tField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 120, -1));

        jLabel3.setText("Gender");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));
        getContentPane().add(gender_tField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 120, -1));

        jLabel4.setText("Course");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));
        getContentPane().add(course_tField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 120, -1));

        jLabel5.setText("Father's Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLabel6.setText("Branch");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));
        getContentPane().add(fathername_tField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 120, -1));
        getContentPane().add(branch_tField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 120, -1));

        jLabel7.setText("Subjects");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel8.setText("Total Marks");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        jLabel9.setText("Passing Marks");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        jLabel10.setText("Marks Obtained");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        jLabel11.setText("Physics");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel12.setText("Chemistry");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel13.setText("Mathematics");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel14.setText("Electricals");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jLabel15.setText("Biology");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        jLabel16.setText("Total");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 446, -1, 10));

        jLabel17.setText("100");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        jLabel18.setText("100");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        jLabel19.setText("100");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        jLabel20.setText("100");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        jLabel21.setText("100");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        jLabel22.setText("30");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        jLabel23.setText("30");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        jLabel24.setText("30");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        jLabel25.setText("30");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        jLabel26.setText("30");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));
        getContentPane().add(total_tField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 100, -1));
        getContentPane().add(physics_tField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 100, -1));
        getContentPane().add(che_tField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 100, -1));

        maths_tField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maths_tFieldActionPerformed(evt);
            }
        });
        getContentPane().add(maths_tField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 100, -1));
        getContentPane().add(ele_tField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 100, -1));
        getContentPane().add(biology_tField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 100, -1));

        jLabel27.setText("Verdict");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 40, -1));
        getContentPane().add(verdict_tField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 100, -1));

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons8-logout-50.png"))); // NOI18N
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 80, 60));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/schoolPic2.png"))); // NOI18N
        jLabel28.setText("jLabel28");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maths_tFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maths_tFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maths_tFieldActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
       String rollNo=rollno_textField.getText();
       try{
           Connection con=ConnectingDatabase.getcon();
           Statement st=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
           ResultSet rs=st.executeQuery("select * from student inner join result where student.RollNumber='"+rollNo+"' AND result.RollNumber='"+rollNo+"'");
           if(!rs.first())
           {
               JOptionPane.showMessageDialog(null, "Roll number doesn't exist");
               
           }
           else
           {
               name_tField.setText(rs.getString(1));
               gender_tField.setText(rs.getString(3));
               fathername_tField.setText(rs.getString(4));
               course_tField.setText(rs.getString(5));
               branch_tField.setText(rs.getString(6));
               
               physics_tField.setText(rs.getString(8));
               che_tField.setText(rs.getString(9));
               maths_tField.setText(rs.getString(10));
               ele_tField.setText(rs.getString(11));
               biology_tField.setText(rs.getString(12));
               total_tField.setText(rs.getString(13));
               
               rollno_textField.setEditable(false);
               name_tField.setEditable(false);
               gender_tField.setEditable(false);
               fathername_tField.setEditable(false);
               course_tField.setEditable(false);
               branch_tField.setEditable(false);
               
               physics_tField.setEditable(false);
               che_tField.setEditable(false);
               maths_tField.setEditable(false);
               ele_tField.setEditable(false);
               biology_tField.setEditable(false);
               total_tField.setEditable(false);
               
               int physicsmarks=Integer.parseInt(rs.getString(8));
               int chemistrymarks=Integer.parseInt(rs.getString(9)); 
               int mathsmarks=Integer.parseInt(rs.getString(10));
               int elemarks=Integer.parseInt(rs.getString(11));
               int biologymarks=Integer.parseInt(rs.getString(12));
               
               if(physicsmarks>=30&&chemistrymarks>=30&&mathsmarks>=30&&elemarks>=30&&biologymarks>=30)
               {
                   verdict_tField.setText("Pass");
               }
               else
               {
                   verdict_tField.setText("Fail");
               }
               
               verdict_tField.setEditable(false);
               
           }
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null, e.toString());
       }
        
    }//GEN-LAST:event_formComponentShown

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
      
        int response=JOptionPane.showConfirmDialog(null, "Are you sure want to exit", "logout", JOptionPane.YES_NO_OPTION);
        if(response==0)
        {
            setVisible(false);
            Home frame=new Home();
            frame.setVisible(true);
            frame.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentResultPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentResultPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentResultPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentResultPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentResultPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField biology_tField;
    private javax.swing.JTextField branch_tField;
    private javax.swing.JTextField che_tField;
    private javax.swing.JTextField course_tField;
    private javax.swing.JTextField ele_tField;
    private javax.swing.JTextField fathername_tField;
    private javax.swing.JTextField gender_tField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField maths_tField;
    private javax.swing.JTextField name_tField;
    private javax.swing.JTextField physics_tField;
    private javax.swing.JTextField rollno_textField;
    private javax.swing.JTextField total_tField;
    private javax.swing.JTextField verdict_tField;
    // End of variables declaration//GEN-END:variables
}
